[tool.black]
    line-length = 99
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | python-env
      | migrations
      | \.tox
    )/
    '''

[tool.isort]
    profile="black"
    line_length = 99
    # force_to_top = file1.py,file2.py
    # skip = file3.py,file4.py
    known_django = ["django"]
    known_first_party = ["dalec", "dalec_example", "dalec_prime"]
    indent = '    '
    multi_line_output = 3
    length_sort = false
    force_single_line = true
    honor_noqa = true
    default_section = "FIRSTPARTY"
    sections  = ["FUTURE", "STDLIB", "PYLIB", "DJANGO",  "FIRSTPARTY", "LOCALFOLDER"]

    combine_as_imports = true

    import_heading_future = "Future imports"
    import_heading_stdlib = "Standard libs"
    import_heading_pylib = "Python libs"
    import_heading_django = "Django imports"
    import_heading_firstparty = "DALEC imports"
    import_heading_localfolder = "Local Apps"
    # force_alphabetical_sort = true

    force_sort_within_sections=true

[tool.djlint]
    profile = "django"
    preserve_blank_lines = true
    format_js = false
    format_css = true

[tool.pyright]
#     exclude = ["python-env"]
    venvPath = "."
    venv = "./python-env"

