[version]
current = "0.2.8"

# valid versions:
# we use semver
# valid syntax are :
# x.y.z-wip for WIP stage (beg dev cycle without releases and not really working)
# x.y.z-[alpha|beta|rc].i for alpha, beta, RC versionning
# x.y.z for stable releases

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (
      (?P<channel>alpha|beta|rc)
      \.
      (?P<release>\d+)
    )
  )?
'''

[git]
message_template = """
EL-LE-VATE to {new_version}
    \\
              ___
      D>=G==='   '.
            |======|
            |======|
        )--/]IIIIII]
           |_______|
           C O O O D
          C O  O  O D
         C  O  O  O  D
         C__O__O__O__D
snd     [_____________]
"""
tag_template = "{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "dalec/__init__.py"
[[file]]
src = "tests_js/package.json"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

 [[before_commit]]
 name = "run tests"
 cmd = "tox -e py39-django22,py39-django32,py39-django42,qa"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
