# Generated by Django 2.2.24 on 2021-11-09 15:15

# Django imports
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("dalec_prime", "0002_auto_20211109_1546")]

    operations = [
        migrations.AlterField(
            model_name="fetchhistory",
            name="channel_object",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="channel app object id",
            ),
        )
    ]
